### ISSUE TITLE
It is recommended to add some tags to the repo

### ISSUE THREAD

**Issue by kerwin612** [egoettelmann/spring-configuration-extensions#4]
It is recommended to add some tags to the repo, similar to: `maven-plugin` `spring-boot` `spring-configuration-metadata` etc.  

This is a very nice library that solves the problem I'm trying to solve, but I had a hard time finding it. Before I found this library, I tried to search it on google/github with some keywords, but the result was not able to locate this library, so I suggest adding some tags to make it easier for people who need it to find it faster.

**Comment by egoettelmann** [comment]
Many thanks for your feedback, and all your contributions.

I added some tags to the repository, hope it makes this repository easier to find.
